sonar.projectKey=devops-portfolio-project
sonar.projectName=DevOps Portfolio Project
sonar.sourceEncoding=UTF-8
sonar.sources=api,frontend
sonar.exclusions=**/node_modules/**,**/venv/**,**/__pycache__/**
